apiVersion: v1
kind: PersistentVolume
metadata:
  name: adls-file-pyspark-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: azure-adls-secret
    shareName: pyspark
    readOnly: false